<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>Hacked.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- https://github.com/CommunityToolkit/Maui/issues/2921 -->
		<NoWarn>NU1608</NoWarn>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		
		<!-- Local macOS dev often has newer Xcode than the currently pinned .NET mobile SDK. -->
		<ValidateXcodeVersion>false</ValidateXcodeVersion>

		<!-- Display name -->
		<ApplicationTitle>Hacked?</ApplicationTitle>
		<!-- Version -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#EF322F" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#EF322F" BaseSize="128,128" />
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.json" LogicalName="Hacked.Maui.appsettings.json" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<EmbeddedResource Include="appsettings.Development.json" LogicalName="Hacked.Maui.appsettings.Development.json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hacked.Core\Hacked.Core.csproj" />
		<ProjectReference Include="..\Hacked.Services\Hacked.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommonHelpers.Maui" Version="0.5.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.51" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
		<PackageReference Include="CommonHelpers" Version="1.5.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Telerik.Licensing" Version="1.8.2" />
		<PackageReference Include="Telerik.UI.for.Maui" Version="13.1.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<PackageReference Include="WinUIEx" Version="2.9.0" />
	</ItemGroup>

  <!-- **************** Windows **************** -->

  <!-- Global Settings -->

  <PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
    <ApplicationId>com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid>61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>
  </PropertyGroup>

  <!-- Debug Settings -->

  <PropertyGroup Condition="$(TargetFramework.Contains('-windows')) and '$(Configuration)' == 'Debug'">
    <WindowsPackageType>None</WindowsPackageType>
    <GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
  </PropertyGroup>

  <!-- Release Sideload Settings -->

  <PropertyGroup Condition="$(TargetFramework.Contains('-windows')) and '$(Configuration)' == 'Release'">
    <WindowsPackageType>MSIX</WindowsPackageType>
    <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
    <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>6317f13d6d4324b3f956e732255c521558ecb235</PackageCertificateThumbprint>
    <UapAppxPackageBuildMode>SideloadOnly</UapAppxPackageBuildMode>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <!-- cli
    msbuild /restore /t:Publish /p:TargetFramework=net10.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=$PFX_THUMBPRINT /p:PackageCe
    rtificatePassword=$PFX_PASSWORD
    
    or with a profile
    dotnet publish D:\Source\GitHub\Hacked\src\Hacked.Maui\Hacked.Maui.csproj -f net10.0-windows10.0.19041.0 -p:PublishProfile=BetaTesters-Windows-MSIX-Bundle
    -->

  <!-- **************** Android **************** -->

	<!-- Global Settings -->

	<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<ApplicationId>com.lancelotsoftware.hacked</ApplicationId>
		<ApplicationIdGuid>61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>
	</PropertyGroup>

  <!-- Release Settings -->

	<!--<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
        <AndroidKeyStore>True</AndroidKeyStore>
        <AndroidSigningKeyStore>dvlup.keystore</AndroidSigningKeyStore>
        <AndroidSigningStorePass>$(android_keystore_password)</AndroidSigningStorePass>
        <AndroidSigningKeyAlias>dvlup.alias</AndroidSigningKeyAlias>
        <AndroidSigningKeyPass>$(android_keystore_alias_password)</AndroidSigningKeyPass>
    </PropertyGroup>-->


	<!-- **************** iOS **************** -->

  <!-- Global Settings -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <ApplicationId>com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid>61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>
  </PropertyGroup>

	<!-- Debug - Simulator
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
	<CodesignKey>Apple Development: Created via API (F85G643H5K)</CodesignKey>
	<CodesignProvision>VS: com.lancelotsoftware.HackedApp Development</CodesignProvision>
  </PropertyGroup>-->

	<!-- Debug - Local iPhone 
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
    <CodesignProvision>Hacked_iOS_Development_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->

	<!-- Release - AdHoc
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>
    <CodesignProvision>Hacked_AdHoc_Distribution_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->

	<!-- Release - App Store
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>
    <CodesignProvision>Hacked_AppStore_Distribution_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->


	<!-- **************** MacCatalyst **************** -->

  <!-- Global -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-maccatalyst'))">
    <ApplicationTitle>Hacked</ApplicationTitle>
    <ApplicationId>com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid>61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>
    <RuntimeIdentifiers>maccatalyst-arm64;maccatalyst-x64</RuntimeIdentifiers>
  </PropertyGroup>

	<!--<PropertyGroup Condition="$(TargetFramework.Contains('-maccatalyst')) and '$(Configuration)' == 'Debug'">
        <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
        <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
        <CodesignProvision>HackedApp_Dev_MacOS_2022.mobileprovision</CodesignProvision>
    </PropertyGroup>-->

	<!--<PropertyGroup Condition="$(TargetFramework.Contains('-maccatalyst')) and '$(Configuration)' == 'Release'">
        <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
        <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>
        <CodesignProvision>HackedApp_MacStore_2022.provisionprofile</CodesignProvision>
    </PropertyGroup>-->



	

</Project>
