<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
    <RollForward>LatestMinor</RollForward>
    <OutputType>Exe</OutputType>
    <RootNamespace>Hacked.Maui</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Display name -->
    <ApplicationTitle>Hacked?</ApplicationTitle>
    <!-- Version -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <!-- Important App Identifiers -->
    <!-- Windows -->
    <ApplicationId Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>

    <!-- MacCatalyst -->
    <ApplicationId Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>

    <!-- iOS -->
    <ApplicationId Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">com.lancelotsoftware.HackedApp</ApplicationId>
    <ApplicationIdGuid Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>

    <!-- Android -->
    <ApplicationId Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">com.lancelotsoftware.hacked</ApplicationId>
    <ApplicationIdGuid Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">61717AC6-F401-4830-B715-78DD35E085CC</ApplicationIdGuid>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hacked.Core\Hacked.Core.csproj" />
    <ProjectReference Include="..\Hacked.Services\Hacked.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageReference Include="CommonHelpers" Version="1.2.1" />
    <PackageReference Include="Telerik.UI.for.Maui" Version="6.6.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <PackageReference Include="WinUIEx" Version="1.8.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-ios'">
    <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
    <CodesignProvision>VS: com.lancelotsoftware.HackedApp Development</CodesignProvision>
  </PropertyGroup>

  <!-- ******** PUBLISHING Android ******** -->

  <!--<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
        <AndroidKeyStore>True</AndroidKeyStore>
        <AndroidSigningKeyStore>dvlup.keystore</AndroidSigningKeyStore>
        <AndroidSigningStorePass>$(android_keystore_password)</AndroidSigningStorePass>
        <AndroidSigningKeyAlias>dvlup.alias</AndroidSigningKeyAlias>
        <AndroidSigningKeyPass>$(android_keystore_alias_password)</AndroidSigningKeyPass>
    </PropertyGroup>-->


  <!-- ******** PUBLISHING iOS ******** -->
    
  <!-- Debug - Simulator
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
    <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
    <CodesignProvision>Hacked_iOS_Development_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->

  <!-- Debug - Local iPhone 
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
    <CodesignProvision>Hacked_iOS_Development_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->

  <!-- Release - AdHoc
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>
    <CodesignProvision>Hacked_AdHoc_Distribution_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->

  <!-- Release - App Store
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <ProvisioningType>manual</ProvisioningType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>
    <CodesignProvision>Hacked_AppStore_Distribution_2023.mobileprovision</CodesignProvision>
  </PropertyGroup>-->


  <!-- ******** PUBLISHING MacCatalyst ******** -->

  <!--<PropertyGroup Condition="$(TargetFramework.Contains('-maccatalyst')) and '$(Configuration)' == 'Release'">
        <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
        <CodesignKey>Apple Distribution: Lancelot Software, LLC (L65255N3F7)</CodesignKey>$(apple_release_codesignIdentity)
        <CodesignProvision>HackedApp_MacStore_2022.provisionprofile</CodesignProvision>
    </PropertyGroup>-->

  <!--<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
        <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
        <CodesignKey>Apple Development: Lance McCarthy (AJ9XMDH9A2)</CodesignKey>
        <CodesignProvision>HackedApp_Dev_MacOS_2022.mobileprovision</CodesignProvision>
    </PropertyGroup>-->


  <!-- ******** PUBLISHING Windows ******** -->

  <!-- This is just like packaging WinUI projects	
    msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=$PFX_THUMBPRINT /p:PackageCe
    rtificatePassword=$PFX_PASSWORD
    -->

</Project>
