name: Build Uno

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
env:
  target-platform: "all"
  sdk_version: '9.0.x'
  NUGET_CONFIG_PATH: 'src/nuget.config'
  TELERIK_NUGET_KEY: ${{secrets.TELERIK_NUGET_KEY}}

jobs:
  smoke_test:
    name: Smoke Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.sdk_version}}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install ${{env.target-platform}} Workloads
        run: |
          dotnet tool install -g uno.check
          uno-check -v --ci --non-interactive --fix --target ${{env.target-platform}} --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates

      - name: Build Hacked (Debug)
        run: msbuild src/Uno/Hacked/Hacked.csproj /r

  unit_test:
    name: Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.sdk_version}}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install ${{env.target-platform}} Workloads
        run: |
          dotnet tool install -g uno.check
          uno-check -v --ci --non-interactive --fix --target ${{env.target-platform}} --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates

      - name: Build Hacked.Tests (Release)
        run: msbuild src/Uno/Hacked.Tests/Hacked.Tests.csproj /p:Configuration=Release /p:OverrideTargetFramework=net8.0 /r

      - name: Run Unit Tests
        run: dotnet test src/Uno/Hacked.Tests/Hacked.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
