name: Build UWP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/Hacked/**/*'
      - 'src/Hacked.BackgroundTasks/**/*'
      - '.github/workflows/build-uwp.yml'

env:
  SOLUTION_PATH: 'src/Hacked_Uwp.slnx'
  Configuration: Debug
  TargetPlatform: x64
  BuildMode: CI
  AppxBundle: Never
  AppxPackageSigningEnabled: False
  DOTNET_SDK_VERSION: '10.0.x'

jobs:
  smoke-test-uwp:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_SDK_VERSION}}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    - name: Build UWP Solution
      run: msbuild ${{env.SOLUTION_PATH}} /t:Restore /p:Configuration=${{env.Configuration}} /p:Platform=${{env.TargetPlatform}} /p:UapAppxPackageBuildMode=${{env.BuildMode}} /p:AppxBundle=${{env.AppxBundle}} /p:AppxPackageSigningEnabled=${{env.AppxPackageSigningEnabled}}
