name: Build Uno

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  smoke_test:
    name: Smoke Test (Debug Build of Hacked)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: LanceMcCarthy/InstallUnoDependencies@v1.0.2
        timeout-minutes: ${{fromJSON(env.STEP_TIMEOUT_MINUTES)}}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.2

      - name: Build Hacked (Debug)
        run: msbuild src/Uno/Hacked/Hacked.csproj /r

  unit_test:
    name: Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: LanceMcCarthy/InstallUnoDependencies@v1.0.2
        timeout-minutes: ${{fromJSON(env.STEP_TIMEOUT_MINUTES)}}
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.2

      - name: Build Hacked.Tests (Release)
        run: msbuild src/Uno//Hacked.Tests/Hacked.Tests.csproj /p:Configuration=Release /p:OverrideTargetFramework=net8.0 /r

      - name: Run Unit Tests
        run: dotnet test src/Uno//Hacked.Tests/Hacked.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
