name: Build Common

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/Hacked.Core/**/*'
      - 'src/Hacked.Services/**/*'
      - '.github/workflows/build-common.yml'

env:
  CORE_PROJECT_PATH: 'src/Hacked.Core/Hacked.Core.csproj'
  SERVICES_PROJECT_PATH: 'src/Hacked.Services/Hacked.Services.csproj'
  NUGETCONFIG_PATH: "src/nuget.config"
  TELERIK_USERNAME: ${{secrets.MyTelerikAccountUsername}}
  TELERIK_PASSWORD: ${{secrets.MyTelerikAccountPassword}}

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.2
      with:
        msbuild-architecture: x64
      
    - name: NuGet Restore
      run: dotnet restore ${{env.SERVICES_PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}
  
    - name: Build Services
      run: msbuild ${{env.SERVICES_PROJECT_PATH}} /p:Platform=x64 /p:Configuration=Debug
