name: Build UWP

on:
  push:
    branches:
      - main
    paths:
      - 'src/Hacked/**/*'
      - 'src/Hacked.BackgroundTasks/**/*'
      - 'src/Hacked.Core/**/*'
      - 'src/Hacked.DataLayer/**/*'
      - 'src/Hacked.Services/**/*'
      - '.github/workflows/main-uwp.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Hacked/**/*'
      - 'src/Hacked.BackgroundTasks/**/*'
      - 'src/Hacked.Core/**/*'
      - 'src/Hacked.DataLayer/**/*'
      - 'src/Hacked.Services/**/*'

env:
  SOLUTION_PATH: 'src/Hacked_Uwp.sln'
  PROJECT_PATH: "src/Hacked/Hacked.csproj"
  NUGETCONFIG_PATH: 'src/nuget.config'

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
      
    - name: NuGet Restore UWP Project
      run: nuget restore ${{ env.PROJECT_PATH }} -ConfigFile ${{ env.NUGETCONFIG_PATH }}
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  
    
    - name: Build UWP Solution
      run: msbuild ${{ env.SOLUTION_PATH }} /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: UWP Artifacts
        path: src\Uwp\SalesDashboard.UWP\bin
