name: Build Common

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/Hacked.Core/**/*'
      - 'src/Hacked.Services/**/*'
      - '.github/workflows/build-common.yml'

env:
  CORE_PROJECT_PATH: 'src/Hacked.Core/Hacked.Core.csproj'
  SERVICES_PROJECT_PATH: 'src/Hacked.Services/Hacked.Services.csproj'
  sdk_version: '10.0.x'
  NUGET_CONFIG_PATH: 'src/nuget.config'
  TELERIK_NUGET_KEY: ${{secrets.TELERIK_NUGET_KEY}}

jobs:
  smoke-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{env.sdk_version}}

    - name: Restore NuGet Packages
      run: dotnet restore ${{env.SERVICES_PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}} 

    - name: Build Services
      run: dotnet build ${{env.SERVICES_PROJECT_PATH}} -c Debug --no-restore
