name: Build .NET MAUI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/Hacked.Maui/**/*'
  #     - '.github/workflows/build-maui.yml'

  workflow_call:
    secrets:
      ANDROID_SIGNING_KEYSTORE_BASE64:
        required: true
      ANDROID_SIGNING_KEYSTORE_FILENAME:
        required: true
      ANDROID_SIGNING_STORE_PASS:  
        required: true
      ANDROID_SIGNING_KEY_ALIAS:
        required: true
      ANDROID_SIGNING_KEY_PASS:  
        required: true

defaults:
  run:
    shell: pwsh

env:
  MACOS_ARTIFACTS_PATH: "artifacts_macos"
  IOS_ARTIFACTS_PATH: "artifacts_ios"
  ANDROID_ARTIFACTS_PATH: "artifacts_android"
  WINDOWS_ARTIFACTS_PATH: "artifacts_windows"
  PROJECT_PATH: "src/Hacked.Maui/Hacked.maui.csproj"
  SDK_VERSION: '10.0.x'
  NET_TFM: 'net10.0'
  NUGET_CONFIG_PATH: 'src/nuget.config'
  TELERIK_NUGET_KEY: ${{secrets.TELERIK_NUGET_KEY}}
  XCODE_VERSION: '26.2'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.SDK_VERSION}}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Install MAUI Workloads
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Add Telerik NuGet Server
        run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}} 

      - name: Build Maui WinUI project
        run: dotnet build ${{env.PROJECT_PATH}} -c Debug -f ${{env.NET_TFM}}-windows10.0.19041.0

      - name: Create artifacts folder
        run: |
           cd ${{github.workspace}}
           mkdir -p ${{env.WINDOWS_ARTIFACTS_PATH}}

      - name: Copy WinUI msix package
        run: Get-Childitem -Path ${{github.workspace}} -Include *.msix -File -Recurse | Copy-Item -Destination ${{env.WINDOWS_ARTIFACTS_PATH}}

      # - name: Publish build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:     
      #     name: "WinUI .NET MAUI artifacts" 
      #     path: "${{env.WINDOWS_ARTIFACTS_PATH}}/*"
      #     if-no-files-found: warn
      #     retention-days: 60

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{env.XCODE_VERSION}}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.SDK_VERSION}}

      - name: Install MAUI Workloads
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Add Telerik NuGet Server
        run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}} 

      - name: Build MacCatalyst App
        run: |
          dotnet build ${{env.PROJECT_PATH}} -f ${{env.NET_TFM}}-maccatalyst -c Debug -p:MtouchLink=SdkOnly
          # dotnet build ${{env.PROJECT_PATH}} -f ${{env.NET_TFM}}-maccatalyst -c Release
          # dotnet publish ${{env.PROJECT_PATH}} -f ${{env.NET_TFM}}-maccatalyst -c Release -p:BuildIpa=True 

      - name: Create artifacts folder
        run: |
           cd ${{github.workspace}}
           mkdir -p ${{env.MACOS_ARTIFACTS_PATH}}
 
      - name: Copy MacOS packages
        run: Get-Childitem -Path ${{github.workspace}} -Include *.pkg -File -Recurse | Copy-Item -Destination ${{env.MACOS_ARTIFACTS_PATH}}

      # - name: Publish macOS build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:     
      #     name: "macOS artifacts" 
      #     path: "${{env.MACOS_ARTIFACTS_PATH}}/*"
      #     if-no-files-found: warn
      #     retention-days: 60

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{env.XCODE_VERSION}}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.SDK_VERSION}}

      - name: Install MAUI Workloads
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Add Telerik NuGet Server
        run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}} 

      - name: Build iOS App
        shell: bash
        run: |
          dotnet build ${{env.PROJECT_PATH}} -f ${{env.NET_TFM}}-ios -c Debug -p:MtouchLink=SdkOnly
          # dotnet publish ${{env.PROJECT_PATH}} -f ${{env.NET_TFM}}-ios -c Release -p:BuildIpa=True

      - name: Create artifacts folder
        run: |
           cd ${{github.workspace}}
           mkdir -p ${{env.IOS_ARTIFACTS_PATH}}

      - name: Copy iOS packages
        run: Get-Childitem -Path ${{github.workspace}} -Include *.app -File -Recurse | Copy-Item -Destination ${{env.IOS_ARTIFACTS_PATH}}

      # - name: Publish iOS build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:     
      #     name: "iOS artifacts" 
      #     path: "${{env.IOS_ARTIFACTS_PATH}}/*"
      #     if-no-files-found: warn
      #     retention-days: 60
  
  build-android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Decode the Keystore
        run: |
          $file_bytes = [System.Convert]::FromBase64String("${{secrets.ANDROID_SIGNING_KEYSTORE_BASE64}}")
          [IO.File]::WriteAllBytes("${{secrets.ANDROID_SIGNING_KEYSTORE_FILENAME}}", $file_bytes)

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.SDK_VERSION}}

      - uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '11'     

      - name: Install MAUI Workloads
        run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

      - name: Add Telerik NuGet Server
        run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}} 

      - name: Simple build MAUI Android
        run: |
          dotnet build ${{env.PROJECT_PATH}} -c Debug -f ${{env.NET_TFM}}-android

      # - name: Publish MAUI Android
      #   run: |
      #     dotnet publish ${{env.PROJECT_PATH}} -c Release -f ${{env.NET_TFM}}-android /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=${{env.ANDROID_SIGNING_KEYSTORE_FILENAME}} /p:AndroidSigningStorePass=${{secrets.ANDROID_SIGNING_STORE_PASS}} /p:AndroidSigningKeyAlias=${{secrets.ANDROID_SIGNING_KEY_ALIAS}} /p:AndroidSigningKeyPass=${{secrets.ANDROID_SIGNING_KEY_PASS}}

      - name: Create artifacts folder
        run: |
           cd ${{github.workspace}}
           mkdir -p ${{env.ANDROID_ARTIFACTS_PATH}}

      - name: Copy signed APKs & AABs
        run: |
           Get-Childitem -Path ${{github.workspace}} -Include *Signed.apk -File -Recurse | Copy-Item -Destination ${{env.ANDROID_ARTIFACTS_PATH}}
           Get-Childitem -Path ${{github.workspace}} -Include *Signed.aab -File -Recurse | Copy-Item -Destination ${{env.ANDROID_ARTIFACTS_PATH}}

      # - name: Publish Android build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:     
      #     name: "Android artifacts" 
      #     path: "${{env.ANDROID_ARTIFACTS_PATH}}/*"
      #     if-no-files-found: warn
      #     retention-days: 60
