name: Release .NET MAUI (tester)

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - 'src/Hacked.Maui/**/*'
  #     - '.github/workflows/release-maui.yml'
  # pull_request:
  #   types: []  # Explicitly disabled - external PRs cannot trigger this workflow

defaults:
  run:
    shell: pwsh

env:
  PROJECT_PATH: "src/Hacked.Maui/Hacked.Maui.csproj"
  SDK_VERSION: '10.0.x'
  NET_TFM: 'net10.0'
  NUGET_CONFIG_PATH: 'src/nuget.config'
  TELERIK_NUGET_KEY: ${{secrets.TELERIK_NUGET_KEY}}
  TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY_VALUE}}

jobs:
  maui-windows-sideload:
    name: Build Windows (Sideload)
    runs-on: [self-hosted, x64, digicert-enabled]
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Generate version number using date and run number
      id: version-creator
      shell: pwsh
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $runNumber = "$env:GITHUB_RUN_NUMBER"
        $ver = $buildDay + "." + $runNumber
        echo "app_version=$ver" >> $env:GITHUB_OUTPUT

    - name: Set Telerik NuGet Credentials
      run: dotnet nuget update source 'Telerik_v3_Feed' -s 'https://nuget.telerik.com/v3/index.json' -u 'api-key' -p "${{secrets.TELERIK_NUGET_KEY}}" --configfile '${{env.NUGET_CONFIG_PATH}}' --store-password-in-clear-text

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGET_CONFIG_PATH}}

    - name: Set API Key
      run: |
        $file = 'src/Hacked.Maui/appsettings.json'
        $config = Get-Content $file -Raw | ConvertFrom-Json
        $config.HibpApiKey = $env:HIBP_API_KEY
        $config | ConvertTo-Json -Depth 10 | Set-Content -Path $file -Encoding utf8NoBOM
      env:
        HIBP_API_KEY: ${{secrets.HIBP_API_KEY}}
          
    - name: Build WinUI project and stage unsigned msixbundle
      id: build-sideload-package
      run: |
        # Unlock certificate using  SafeNet authentication client (USB hardware token must be plugged in)
        $sacTools = "C:\Program Files\SafeNet\Authentication\SAC\x64\SACTools.exe"
        & $sacTools /Token /LogOn /Password "${{secrets.DIGICERT_HARDWARE_TOKEN_PASSWORD}}"

        $thumbprint = "8BC202959D2DCE3EEB3A489D8348B5C9B6B64A97"
        $cn="CN='Lancelot Software, LLC', OU=IoT, O='Lancelot Software, LLC', L=NORTH BILLERICA, S=Massachusetts, C=US"

        dotnet publish ${{env.PROJECT_PATH}} -c Release -f ${{env.NET_TFM}}-windows10.0.19041.0 -p:AppxPackageSigningEnabled=true -p:UapAppxPackageBuildMode=SideloadOnly -p:AppxBundle=Always "-p:AppxBundlePlatforms=x64|arm64" -p:PlatformTarget=AnyCPU -p:PackageCertificateThumbprint=$thumbprint -p:AppxPackageCertificateSubjectName=$cn -p:AppxPackageVersion="${{steps.version-creator.outputs.app_version}}.0" -p:AppxPublisherDisplayName="Lancelot Software"

    - name: Locate msixbundle
      id: find-msix-file
      run: |
        $msixPath = Get-ChildItem -Filter Hacked*.msixbundle -Recurse | Select-Object -ExpandProperty FullName -First 1
        if (-not $msixPath) { throw "No .msixbundle found after publish" }
        echo "PACKAGE_PATH=$msixPath" >> $env:GITHUB_OUTPUT

    # - name: Use hardware token and sign with digicert certificate
    #   run: |
    #     # Launch SafeNet authentication client (USB hardware token must be plugged in)
    #     # Unlock token via SafeNet's PKCS#11 interface; this will prompt for PIN entry if token is locked
    #     $sacTools = "C:\Program Files\SafeNet\Authentication\SAC\x64\SACTools.exe"
    #     & $sacTools /Token /LogOn /Password "${{secrets.DIGICERT_HARDWARE_TOKEN_PASSWORD}}"

    #     # Now the cert is ready to be used for signing. Sign the package with a timestamp.
    #     $signtool = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\signtool.exe"
    #     & $signtool sign /sha1 8BC202959D2DCE3EEB3A489D8348B5C9B6B64A97 `
    #       /fd sha256 `
    #       /tr http://timestamp.digicert.com `
    #       /td sha256 `
    #       "${{steps.build-sideload-package.outputs.bundle_path}}"

    - name: Attach artifacts to workflow run
      uses: actions/upload-artifact@v7
      with:     
        name: "Hacked_v${{steps.version-creator.outputs.app_version}}_sideload"
        path: ${{steps.find-msix-file.outputs.PACKAGE_PATH}}
        if-no-files-found: error
        retention-days: 30
